### ISSUE TITLE
Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by JunhwonKim** [Wujiaxuan007/YourProgressBar#3]
### Stacktrace
Please paste the full stacktrace from the IDEA error popup.

```
java.lang.NullPointerException
	at pers.wjx.plugin.ProgressBarConfigForm.initComponent(ProgressBarConfigForm.java:127)
	at pers.wjx.plugin.ProgressBarConfigForm.<init>(ProgressBarConfigForm.java:50)
	at pers.wjx.plugin.progress.ProgressBarConfigurable.isModified(ProgressBarConfigurable.kt:37)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.isModified(ConfigurableWrapper.java:174)
	at com.intellij.openapi.options.newEditor.SettingsEditor.checkModifiedInternal(SettingsEditor.java:520)
	at com.intellij.openapi.options.newEditor.SettingsEditor.checkModifiedForItem(SettingsEditor.java:514)
	at com.intellij.openapi.options.newEditor.SettingsEditor.checkModified(SettingsEditor.java:502)
	at com.intellij.openapi.options.newEditor.SettingsEditor$4.onSelected(SettingsEditor.java:157)
	at com.intellij.openapi.options.newEditor.OptionsEditorContext$1.process(OptionsEditorContext.java:44)
	at com.intellij.openapi.options.newEditor.OptionsEditorContext.lambda$notify$0(OptionsEditorContext.java:104)
	at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:1880)
	at com.intellij.openapi.options.newEditor.OptionsEditorContext.notify(OptionsEditorContext.java:104)
	at com.intellij.openapi.options.newEditor.OptionsEditorContext.fireSelected(OptionsEditorContext.java:40)
	at com.intellij.openapi.options.newEditor.SettingsTreeView.fireSelected(SettingsTreeView.java:455)
	at com.intellij.openapi.options.newEditor.SettingsTreeView$5.lambda$run$0(SettingsTreeView.java:430)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1823)
	at com.intellij.ide.util.treeView.AbstractTreeUi.runDone(AbstractTreeUi.java:4214)
	at com.intellij.ide.util.treeView.AbstractTreeUi$63.perform(AbstractTreeUi.java:3980)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:20)
	at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:177)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.ide.util.treeView.AbstractTreeUi$64.perform(AbstractTreeUi.java:4005)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:20)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1823)
	at com.intellij.ide.util.treeView.AbstractTreeUi.runDone(AbstractTreeUi.java:4214)
	at com.intellij.ide.util.treeView.AbstractTreeUi.selectVisible(AbstractTreeUi.java:3960)
	at com.intellij.ide.util.treeView.AbstractTreeUi$62.perform(AbstractTreeUi.java:3944)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:20)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:121)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1070)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:702)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:439)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1656)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1614)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:90)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:50)
	at com.intellij.ui.mac.MacOSApplicationProvider$Worker.lambda$initMacApplication$1(MacOSApplicationProvider.java:74)
	at com.intellij.ui.mac.MacOSApplicationProvider$Worker.lambda$submit$8(MacOSApplicationProvider.java:174)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(Ev...
```

### Version and Environment Details
Operation system: macOS 13.3.1
IDE version: AI-221.6008.13.2211.9619390
Plugin version: 1.01

**Comment by Wujiaxuan007** [comment]
This problem is probably solved in version 1.1. 1.1 is under review, please wait for one or two days ：）
